version: '3.8'

services:
  # O Banco de Dados
  db:
    image: postgres:15
    container_name: synapse_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: synapse_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Interface visual para ver o banco (tipo um Workbench/Dbeaver no navegador)
  pgadmin:
    image: dpage/pgadmin4
    container_name: synapse_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data: